package io.github.ih0rd.codegen;

import io.github.ih0rd.contract.ContractClass;
import io.github.ih0rd.contract.ContractMethod;
import io.github.ih0rd.contract.ContractParam;
import java.util.StringJoiner;

/// # JavaInterfaceGenerator
///
/// Generates Java interface source code from a contract model.
///
/// This generator produces **pure Java contracts** without any runtime or framework-specific annotations.
///
/// Responsibilities:
/// - Generate package and interface declaration
/// - Generate JavaDoc for interface and methods
/// - Render method signatures in a stable format
///
/// Design notes:
/// - No Spring dependencies
/// - No runtime annotations
/// - Output is deterministic and formatter-friendly
///
public final class JavaInterfaceGenerator {

    private static final String GENERATED_HEADER =
            """
                    /// Auto-generated polyglot contract.
                    ///
                    /// This file was generated by polyglot-codegen.
                    /// Do not modify this file manually.
                    
                    """;

    /// ### generate
    ///
    /// Generates Java interface source code for the given contract class.
    ///
    /// @param contract contract class model
    /// @return Java interface source code
    public String generate(ContractClass contract) {
        StringBuilder sb = new StringBuilder();

        // header
        sb.append(GENERATED_HEADER);

        // interface declaration
        sb.append("public interface ")
                .append(contract.name())
                .append(" {\n\n");

        for (ContractMethod method : contract.methods()) {
            sb.append(renderMethod(method))
                    .append("\n");
        }

        sb.append("}\n");
        return sb.toString();
    }

    private String renderMethod(ContractMethod method) {
        StringBuilder sb = new StringBuilder();

        // JavaDoc
        sb.append("    /// ")
                .append(method.name())
                .append("\n");

        for (ContractParam param : method.params()) {
            sb.append("    /// @param ")
                    .append(param.name())
                    .append("\n");
        }

        sb.append("    /// @return ")
                .append(method.returnType())
                .append("\n");

        // signature
        sb.append("    ")
                .append(method.returnType())
                .append(" ")
                .append(method.name())
                .append("(")
                .append(renderParams(method))
                .append(");\n");

        return sb.toString();
    }

    private String renderParams(ContractMethod method) {
        StringJoiner joiner = new StringJoiner(", ");

        for (ContractParam param : method.params()) {
            joiner.add(param.type() + " " + param.name());
        }

        return joiner.toString();
    }
}
