package io.github.ih0rd.codegen;

import io.github.ih0rd.contract.ContractClass;
import io.github.ih0rd.contract.ContractMethod;
import io.github.ih0rd.contract.ContractParam;

import java.util.Set;
import java.util.StringJoiner;
import java.util.TreeSet;

/// # JavaInterfaceGenerator
///
/// Generates Java interface source code from a contract model.
///
/// Responsibilities:
/// - Render method signatures
/// - Collect required imports
/// - Produce deterministic, clean output
///
/// Design notes:
/// - Uses {@link JavaTypeRenderer} for type rendering
/// - Automatically injects imports
/// - No framework annotations
/// - No runtime logic
///
public final class JavaInterfaceGenerator {

    private static final String GENERATED_HEADER =
            """
            /// Auto-generated polyglot contract.
            ///
            /// This file was generated by polyglot-codegen.
            /// Do not modify this file manually.

            """;
    JavaTypeRenderer renderer = new JavaTypeRenderer();

    /// ### generate
    ///
    /// Generates full Java interface source.
    ///
    public String generate(ContractClass contract) {

        StringBuilder body = new StringBuilder();

        // render methods first (so imports get collected)
        for (ContractMethod method : contract.methods()) {
            body.append(renderMethod(method)).append("\n");
        }

        Set<String> imports = new TreeSet<>(renderer.getImports());

        StringBuilder file = new StringBuilder();

        file.append(GENERATED_HEADER);

        // imports
        if (!imports.isEmpty()) {
            for (String imp : imports) {
                file.append("import ").append(imp).append(";\n");
            }
            file.append("\n");
        }

        // interface declaration
        file.append("public interface ")
                .append(contract.name())
                .append(" {\n\n");

        file.append(body);

        file.append("}\n");

        return file.toString();
    }

    /// ### renderMethod
    ///
    /// Renders a single method signature.
    ///
    private String renderMethod(ContractMethod method) {

        StringBuilder sb = new StringBuilder();

        String returnType = renderer.render(method.returnType());

        sb.append("    ")
                .append(returnType)
                .append(" ")
                .append(method.name())
                .append("(")
                .append(renderParams(method))
                .append(");\n");

        return sb.toString();
    }

    /// ### renderParams
    ///
    /// Renders parameters using renderer.
    ///
    private String renderParams(ContractMethod method) {

        StringJoiner joiner = new StringJoiner(", ");

        for (ContractParam param : method.params()) {
            joiner.add(
                    renderer.render(param.type()) + " " + param.name()
            );
        }

        return joiner.toString();
    }
}